site_name: Improved Local Assistant
site_description: Production-ready local AI assistant with GraphRAG technology and voice interface
site_url: https://hugokos.github.io/improved-local-assistant
repo_url: https://github.com/hugokos/improved-local-assistant
repo_name: hugokos/improved-local-assistant

# Point to the top-level docs directory relative to this config file
docs_dir: ../docs
site_dir: ../site

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - User Guides:
    - Prebuilt Graphs: PREBUILT_GRAPHS_GUIDE.md
    - Graph Download System: GRAPH_DOWNLOAD_SYSTEM.md
    - Property Graph Migration: PROPERTY_GRAPH_MIGRATION.md
    - Memory Fallback System: MEMORY_FALLBACK_SYSTEM.md
    - Storage & Persistence: STORAGE_AND_PERSISTENCE_TESTING.md
  - Voice Interface:
    - Voice Chat Implementation: VOICE_CHAT_IMPLEMENTATION.md
    - Voice Control Fixes: VOICE_CONTROL_FIXES.md
    - Voice Phase 1: VOICE_PHASE1_IMPLEMENTATION.md
    - Voice Phase 2: VOICE_PHASE2_IMPLEMENTATION.md
  - Technical Guides:
    - Edge Chrome Audio Fixes: EDGE_CHROME_AUDIO_FIXES.md
    - Edge Optimization: EDGE_OPTIMIZATION.md
  - API Reference:
    - API Documentation: API.md
  - Architecture:
    - Project Structure: adr/001-project-structure.md
  - Project Info:
    - Development History: DEVELOPMENT_HISTORY.md
    - Changelog: CHANGELOG.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hugokos/improved-local-assistant
    - icon: fontawesome/solid/book
      link: https://hugokos.github.io/improved-local-assistant