name: ci

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Type check
        run: mypy src || echo "Type checking completed with issues"
      - name: Test (with coverage)
        run: pytest -q --cov=improved_local_assistant --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          verbose: true

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install security tools
        run: |
          pip install bandit[toml] safety
      - name: Run Bandit
        run: bandit -r src/ -f json -o bandit-report.json || true
      - name: Run Safety
        run: safety check --json --output safety-report.json || true