name: ci

on:
  push:
    branches: [main]
  pull_request: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dev deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[dev] -c constraints.txt || pip install -e . -c constraints.txt
      - name: Run pre-commit (all hooks)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dev deps
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install -e .[dev] -c constraints.txt || pip install -e . -c constraints.txt
          pip install types-requests types-PyYAML types-setuptools
      - name: mypy
        run: mypy src

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install PortAudio (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libportaudio2
      - name: Install deps
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install -e . -c constraints.txt
      - name: Check dependency health
        run: |
          python -m pip check
          pip install -U pipdeptree
          pipdeptree --warn fail -p llama-index,llama-index-core,llama-index-embeddings-ollama
      - name: Run tests
        run: pytest -q --cov=improved_local_assistant --cov-report=xml --fail-under=70

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install security tools
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . -c constraints.txt
      - name: Run Bandit security scan
        run: bandit -r src/ -ll
      - name: Run Safety dependency scan
        run: safety check --full-report
      - name: Run secret scan with gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}