name: ci (temporarily disabled)

on:
  workflow_dispatch: {}  # manual only

permissions:
  contents: read

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI temporarily disabled during test suite refactor"
