name: docs (temporarily disabled)

on:
  workflow_dispatch: {}  # manual only

permissions:
  contents: write

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docs workflow temporarily disabled during test suite refactor"
