name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install MkDocs + plugins
        run: |
          python -m pip install -U pip
          pip install mkdocs mkdocs-material mkdocstrings[python]
      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Build & deploy
        run: mkdocs gh-deploy --force --config-file config/mkdocs.yml